// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBK_xZ5Hii9OAOUSopqjm-UsxG6NuhRa4',
    appId: '1:674226730150:web:238921701d85ab3498f067',
    messagingSenderId: '674226730150',
    projectId: 'bookly-44433',
    authDomain: 'bookly-44433.firebaseapp.com',
    storageBucket: 'bookly-44433.appspot.com',
    measurementId: 'G-C94LH0NJS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjbFXcYt8FG0Oog8RwdecLUCrsGD9xpVg',
    appId: '1:674226730150:android:a9b5ad5b1b966ede98f067',
    messagingSenderId: '674226730150',
    projectId: 'bookly-44433',
    storageBucket: 'bookly-44433.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN9A86O1CepzQ61WTjkbfYxZnx5It4mxI',
    appId: '1:674226730150:ios:5df67a530f703ce398f067',
    messagingSenderId: '674226730150',
    projectId: 'bookly-44433',
    storageBucket: 'bookly-44433.appspot.com',
    iosBundleId: 'com.example.bookly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN9A86O1CepzQ61WTjkbfYxZnx5It4mxI',
    appId: '1:674226730150:ios:5df67a530f703ce398f067',
    messagingSenderId: '674226730150',
    projectId: 'bookly-44433',
    storageBucket: 'bookly-44433.appspot.com',
    iosBundleId: 'com.example.bookly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBK_xZ5Hii9OAOUSopqjm-UsxG6NuhRa4',
    appId: '1:674226730150:web:1dce56eafa90afd298f067',
    messagingSenderId: '674226730150',
    projectId: 'bookly-44433',
    authDomain: 'bookly-44433.firebaseapp.com',
    storageBucket: 'bookly-44433.appspot.com',
    measurementId: 'G-7JR7QBWFL1',
  );

}